### ISSUE TITLE
Callback on successful booking?

### ISSUE THREAD

**Issue by dschuermann** [meetergo/meetergo-integration#13]
Hi,

is there any way to get a callback after a successful booking happened?

We are currently using cal.com which allows this:
```
Cal("on", {
  action: "bookingSuccessful",
    callback: (e)=>{
    	const {data, type, namespace} = e.detail;
      
    }
})
```

**Comment by boy51** [comment]
Yes we can make a prop to pass in `onSuccess` in `meetergoSettings`. Does that work for you?

**Comment by dschuermann** [comment]
@boy51 that would be perfect, can you also add an example for the embed code?

**Comment by boy51** [comment]
@dschuermann Sure, could you clarify what the example should achieve? I'm not sure that I got it

**Comment by boy51** [comment]
If you mean for `onSuccess`, sure will include an exapmle

**Comment by dschuermann** [comment]
@boy51 yep, that's what I meant

**Comment by dschuermann** [comment]
@boy51 Any update? :grinning: We are really looking forward to switching to a EU alternative for our calendar bookings.

**Comment by AzooraDev** [comment]
Hey, is there something new to this issue. I want to use a callback `onSuccess` too. For example to access it with window.addEventListener.

**Comment by dschuermann** [comment]
@meetergo update?

**Comment by dschuermann** [comment]
Thanks!
