### ISSUE TITLE
Code Generator seems broken

### ISSUE THREAD

**Issue by boldtrn** [meetergo/meetergo-integration#8]
This is the code I get for a popup:

```
<!-- meetergo widget start --><script>
    window.meetergoSettings = {
      floatingButton: {
        position: "top-left",
        text: Book a meeting,
        link: https://my.meetergo.com/form/f72cdcb2-.[REDACTED],
        backgroundColor: #3182CE,
        textColor: #FFFFFF
      },
    };
  </script><!-- meetergo widget end -->
```

As you can see the text, link, etc. don't contain proper string markup. So it should be:

```
        text: "Book a meeting",
```

Also the async script tag is missing completely:
```
<script
  async
  src="https://cdn.jsdelivr.net/gh/meetergo/meetergo-integration/dist/esbuild/browser.js"
></script>
```

<img width="740" alt="Screenshot 2023-02-12 at 17 46 03" src="https://user-images.githubusercontent.com/1553525/218324589-d37f7a76-86ab-45b5-b014-5cd971a2b66c.png">

**Comment by KostiantynMeetergo** [comment]
Thank you for submitting the issue. 
We appreciate your effort in bringing this to our attention. 
This will be fixed with the next release/deploy.
